# Generated by Django 6.0.3 on 2026-03-24 21:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VehicleType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('extra_rate', models.DecimalField(decimal_places=2, default=0.0, help_text='Supplément pour ce type', max_digits=6)),
            ],
        ),
        migrations.AlterField(
            model_name='zone',
            name='max_duration',
            field=models.IntegerField(help_text='En heures'),
        ),
        migrations.AlterField(
            model_name='zone',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, help_text='Prix de base de la zone', max_digits=6),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='vehicle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.vehicletype'),
        ),
    ]
